site_name: 8008幸福宝app软件大全
site_author: 8008幸福宝app软件大全
site_description: 8008幸福宝app为你提供最新热播电影电视剧免费在线观看,无须VIP即可超前点播全网影视资源,超快的播放速度给你不一样的观影体验。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
